USE HOSPITALS;

-- Find services that have admitted more than 500 patients in total.
SELECT SERVICE, SUM(PATIENTS_ADMITTED) AS TOTAL_PATIENTS
FROM SERVICES_WEEKLY
GROUP BY SERVICE
HAVING TOTAL_PATIENTS >500;

-- Show services where average patient satisfaction is below 75.
SELECT SERVICE, AVG(PATIENT_SATISFACTION) AS AVERAGE_PATIENTS_SATISFACTION
FROM SERVICES_WEEKLY
GROUP BY SERVICE
HAVING AVERAGE_PATIENTS_SATISFACTION <75;

-- List weeks where total staff presence across all services was less than 50
SELECT WEEK, COUNT(STAFF_ID) AS TOTAL_STAFF 
FROM STAFF_SCHEDULE 
WHERE PRESENT = 1
GROUP BY WEEK
HAVING TOTAL_STAFF <50 ;

-- Identify services that refused more than 100 patients in total and had an average patient satisfaction below 80. 
-- Show service name, total refused, and average satisfaction.

SELECT SERVICE, SUM(PATIENTS_REFUSED) AS TOTAL_PATIENTS_REFUSED, AVG(PATIENT_SATISFACTION) AS AVERAGE_PATIENT_SATISFACTION
FROM SERVICES_WEEKLY
GROUP BY SERVICE
HAVING SUM(PATIENTS_REFUSED) >100 AND AVERAGE_PATIENT_SATISFACTION <80;
